name: Push

on:
  push:
    branches: [ main ]

jobs:
  Dust:
    name: Duster
    uses: ./.github/workflows/duster-fix-blame.yml
    permissions:
      contents: write
  Test:
    needs: dust
    name: Run Tests
    uses: ./.github/workflows/pest.yml